### ISSUE TITLE
Support for NX-8SE?

### ISSUE THREAD

**Issue by lexpostma** [flareman/homebridge-caddx-interlogix#11]
Just a newbie question, but would you expect this plugin to also work with the NetworX NX-8SE alarm system? Or is it specific to your NX-595E?

**Comment by flareman** [comment]
From what I gather, NX-8SE is the Dutch version of NX-8E. All the prior NetworX (NX) series boards (namely, NX-4, NX-6 and NX-8 and their derivatives) support the NX-595E, and from what I know they don't support out-of-the-box IP connectivity. NGX (xGen) boards have native IP support, however, but the plugin does not support those, as I don't have a device on hand for testing, sadly.

Does your NX-8SE really have native IP support, or maybe you have an xGen model installed?

**Comment by lexpostma** [comment]
Hi Spyros, thanks for your reply. Yesterday I finally had a chance to dig in. I created a new 'homebridge' user via the web interface of the alarm and configured the plugin. I guess I do have native IP support. Everything worked out of the box, truly amazing work!

* The alarm has 3 states for off, home and away
* All the sensors are in HomeKit
* Even the doorbell chime is there as a separate switch

I'm a happy man!

The only thing that was a bit unreliable was setting the alarm to "Home". When switched, it did arm the alarm, but in HomeKit is moved to "Away". From the alarm's web UI I could see it was in fact on "Home". It's hard for you to test of course without the device, but can you help me fix this?

**Comment by flareman** [comment]
Could you please try to restart the homebridge server? Sometimes after the initial setup the alarm state gets stuck when changing, which is resolved with a simple restart done just once.

Also, bear in mind that while the alarm is arming the plug-in reports the alarm as "away", because the interface provides no way to discern between arming for away and arming from home. After the arm countdown period has passed, it should report the proper status.

Please check this and report back to me so we can figure this out :)

**Comment by lexpostma** [comment]
You're right, it does switch to Home after the cool-down period. Takes a bit longer than expected, but that's good to know. I thought I'd be 10 seconds, but it's about a minute or so. Either way, I'm a happy camper. Looking forward to using the plugin. If I run into anything, I know where to ask. Thanks again!

**Comment by flareman** [comment]
No worries, glad you could take advantage of the plug-in ✌🏻
