### ISSUE TITLE
Hide chime button

### ISSUE THREAD

**Issue by stuntman999** [flareman/homebridge-caddx-interlogix#13]
Hi, is it possible to add an option to remove the chime button?   It's not working with my touchscreen keypad as the chime seems to be controlled directly in the keypad instead of the panel...

Thank you for this really good plugging!!

**Comment by flareman** [comment]
Hello and thanks for you kindness :)

The chime switch is registered as part of the area alarm accessory. You can select the "display as separate tiles" option in HomeKit and then move the chime switch to whatever room you wish. I'm guessing the keypad you refer to is a hardware component? Theoretically the HomeKit chime switch should reflect the chime status as it is set from the hardware alarm controls, regardless of their kind. Is that not the situation in your case?

**Comment by stuntman999** [comment]
Hello, I have this keypad [NetworX Touch Screen Keypad](https://www.interlogix.com/intrusion/product/networx-touch-screen-keypad).  It have customizable chime groups for speciﬁc zones so its not using whats in the panel...  This is why the chime button in Homekit doesn't do anything for this keepad... I just did what you suggested and move the chime button to another room and remove it from favorites.  I'm searching also if there's a way for this keypad to use chime setting from the panel.. Let me know if you know something about this..  Thank you!

**Comment by flareman** [comment]
The communication between my plugin and the alarm motherboard happens via the NX-595E network interface module, which AFAIK does not support separate chime regions, so I don't know how to customize that (and I don't have the required equipment to start testing, sadly). I could add a feature to disable the chime switch in HomeKit if that's what you need, but it might take some time due to real life obligations. Still, that won't solve your main issue, which is disabling (?) the chime in general; that would be a keypad matter.
