### ISSUE TITLE
Card continues to crash

### ISSUE THREAD

**Issue by doncarajo** [flareman/homebridge-caddx-interlogix#18]
Hi again! So after your plug in was working very well for a number of days I started getting the dreaded SSL error again. They became more frequent after I reset the card from the security panel and now it's to the point that the card locks itself into SSL mode every few seconds. I downgraded to v1.22 and the same thing happens so I suspect it's a hardware thing. The only thing I haven't done is take the power off the card which I will probably try later, it's just awkward. Which card do you use? I remember you saying you had a different version to mine. I wonder if I can buy that and install it.

**Comment by flareman** [comment]
That's very unfortunate to hear 🤬 I have an NX6v2 system with the NX595E network module installed with the ComNav 0.108O firmware revision installed on the latter.

SSL errors theoretically occur when attempting to connect via https to the web interface (and are caused by a deprecated TLS/SSL cipher suite that it uses). The installer manual explicitly states that SSL access is not supported anymore as its implementation is too old; the old manual mentions Location 19, option 2 as the SSL setting (has to be turned off to allow standard http connections), which can be set using the standard programming using the control panel of the alarm installation (typically starting with *8 -> [master PIN] -> 191#, and then changing the option value as usual). Please do note that tampering with the control panel and system settings can mess up your installation severely, so it would be best to do this with your security technician's help.

That being said, the plugin explicitly uses http:// calls, so other than the idea described above, I really have nothing else to suggest, and there is no practical way to force an SSL connection, short of installing a custom-build version of both node and the plugin itself to allow for the ancient cipher suite; needless to say, this is both dangerous and impractical, sadly.

I'll leave the issue open for a while; feel free to get back in touch with any kind of updates 🙏🏻✌🏻

**Comment by doncarajo** [comment]
Hi mate. I have become quite familiar with resetting the module. What happens is that everything is working fine then the module crashes and turns on the SSL by ITSELF. The only way to access the webpage then becomes by resetting the whole thing and disabling SSL (and redoing the options properly). I can crash the module now by just refreshing the webpage too many times. I suspect the polling from your plug in has the same effect.

**Comment by flareman** [comment]
It really shouldn't lock up like this; all I can suggest is reducing the polling frequency (increasing the polling interval), to reduce calls to the web interface. EDIT: The web interface polls every 5500 ms from what I can see in their Javascript, so I guess that would work without faults; of course, that means waiting for 5,5 seconds for HomeKit to update the displayed sensor states. The NX-595E is a hot mess coding-wise, the integrated HTTP server that the module serves respects close to no common practices, and its behavior is erratic outside the web interface (and, sometimes, within the web interface as well). It's unfortunate that there are no firmware upgrades to be expected too. What versions are you running? You could see this in the web interface -> Feature Setup (firmware, hardware, bootload, and web version fields).

**Comment by doncarajo** [comment]
Hi. The module just has become increasingly sensitive to poll requests. It is quite brittle now. Firmware 2.0k, hardware 1.0, bootload 4.0, web version CN_0.106-j. I increased the polling time to 10 secs but it still crashes it. Surely the hardware is now faulty?

**Comment by flareman** [comment]
My module is running firmware A55P003001-03, hardware 206144IX12, bootloader B0402002, web version CN_0.108-O; maybe this older version works bad with multiple polling requests? Then again it *was* working in the past, so maybe it is just going faulty. If you had access to a second network module that's known to work, you could replace the present one with the good one and check for crashes, but I'm guessing this is taking it a bit too far 🤷 I just don't see how or why the module should crash when polled multiple times; even the web interface polls every 5500 ms, and that's by design from Interlogix. If you log in the web interface and leave it logged in like that for an extended period of time, will it crash too?

**Comment by doncarajo** [comment]
If I leave the webpage open it doesn’t to crash. If I reload the webpage a
few times it does crash. I agree that because it used to work, that the
card is probably going faulty. I’ll see if I can get another card to check
it out. Will keep you updated. You can probably close this issue as it
seems related to the hardware not your software. Thank you.

**Comment by flareman** [comment]
Thanks so much for your continued support debugging the plugin 🙏🏻
